### ISSUE TITLE
null pointer exception in delete

### ISSUE THREAD

**Issue by magwas** [magwas/zenta#44]
java.lang.NullPointerException
	at org.rulez.magwas.zenta.model.impl.DiagramModelComponentBase.deleteObjectClassIfItIsTemplate(DiagramModelComponentBase.java:462)
	at org.rulez.magwas.zenta.model.impl.DiagramModelComponentBase.deleteObjectClassIfItIsZentaObjectInTemplate(DiagramModelComponentBase.java:459)
	at org.rulez.magwas.zenta.model.impl.DiagramModelComponentBase.deleteObjectFromContainer(DiagramModelComponentBase.java:450)
	at org.rulez.magwas.zenta.model.impl.DiagramModelComponentBase.delete(DiagramModelComponentBase.java:444)
	at org.rulez.magwas.zenta.model.impl.DiagramModelComponentBase.delete(DiagramModelComponentBase.java:429)
	at org.rulez.magwas.zenta.model.impl.ZentaElementBase.deleteDiagramObjects(ZentaElementBase.java:679)
	at org.rulez.magwas.zenta.model.impl.ZentaElementBase.delete(ZentaElementBase.java:662)
	at org.rulez.magwas.zenta.model.impl.BasicObjectBase.delete(BasicObjectBase.java:407)
	at org.rulez.magwas.zenta.editor.model.commands.DeleteCommand.execute(DeleteCommand.java:32)
	at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:199)
	at org.rulez.magwas.zenta.editor.views.tree.actions.DeleteAction.deleteUsingCommandStack(DeleteAction.java:75)
	at org.rulez.magwas.zenta.editor.views.tree.actions.DeleteAction.run(DeleteAction.java:65)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.rulez.magwas.zenta.editor.Application.start(Application.java:69)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by magwas** [comment]
most probably fixed in feature/deletebugs
